name: test

on: [pull_request]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
        - name: Checkout source repository                                  
          uses: actions/checkout@v2
        # - name: Login to Docker                                
        #   uses: docker/login-action@v1
        #   with:
        #     registry: ghcr.io
        #     username: ${{ github.repository_owner }}
        #     password: ${{ secrets.DOCKER_CONTINER_REGISTRY_TOKEN }}
        - name: Download state src
          run: |
            curl -H "Authorization: token ${STATE_SRC_TOKEN} " \
              -H 'Accept: application/vnd.github.v3.raw' \
              -O \
              -L https://api.github.com/repos/uedar/state-private/contents/state-5.6.10.tgz
          env: 
            STATE_SRC_TOKEN: ${{ secrets.STATE_SRC_TOKEN }}
        - name: Build docker
          run: |
            docker compose build
            docker compose up -d
          env: 
            state_src: ./state-5.6.10.tgz
        - name: debug
          run: sudo usermod -a -G docker runner
        - name: Run pytest                                       
          run: docker compose exec --user 1000 state_interface pytest /home/test_user/ase-state-interface
  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          flake8_args: "--max-line-length 119"
