name: reviewdog

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: poetry install --no-interaction

  pytest:
    runs-on: ubuntu-latest
    name: pytest
    needs: setup
    steps:
      - name: Run Tests
        run: poetry run pytest tests

  pylint:
    runs-on: ubuntu-latest
    name: pylint
    needs: setup
    steps: 
      - name: Setup pylint
        run: |
          pylint --generate-rcfile > ~/.pylintrc
          echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      - name: Run pylint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pylint --rcfile=~/.pylintrc $(git ls-files '*.py') | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review -fail-on-error=true -diff="git diff FETCH_HEAD"

  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8
    needs: setup
    steps:
      - name: flake8 Lint
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
